### ISSUE TITLE
Add support and docs for configuring multiple external auth providers

### ISSUE THREAD

**Issue by dkleissa** [gigantum/hybrid-object-store#232]
Dex supports this, but test and document the process to configure Azure AD (or ldap) + another TBD external auth provider.

**Tasks**
- [ ] Update makefile to create new cert directory
- [ ] Update dex to mount cert directory
- [ ] Update auth service to allow setting the issuer
- [ ] (Docs) Finish document explaining how to set up azure and dex
