### ISSUE TITLE
Add multi-search index support

### ISSUE THREAD

**Issue by dkleissa** [gigantum/hybrid-object-store#296]
This issue is to update the system to support updating multiple search indices (i.e. in two servers that are on different networks). This issue will effectively complete https://github.com/gigantum/hybrid-object-store/issues/195. 

While a single index would be easier to maintain for an admin, there is a high likelihood that all servers won't have access to the single index. A more reliable solution is to have each core service maintain its own opensearch index that the single sync service updates via new core service endpoints. The benefit of this is that all opensearch code is centralized in the core service.

## Tasks
- [x] Add config value to the sync service, indicating which search indices should be updated. Default to the local core service.
- [x] Move index creation to the core service startup
- [x] Add core service endpoint to add/update the search index for a given file that is only available to the service account
- [x] Add core service endpoint to remove the search index entry for a given file that is only available to the service account
- [ ] Update search endpoints to support specifying the server where the data is located (add core service endpoint to the query)
- [ ] Update sync service to use core services + new API endpoints to make metadata update requests (multiple requests if there are more than one core services listed)
  -  Waiting on sync service updates. It's likely that we can allow service account events through just for metadata updates and that should enable "multiple servers"
- [x] (Clean up from auto-complete) Update UI to use metadata endpoint when trying to load metadata for an object, if running on s3
