### ISSUE TITLE
Create system for loading existing dataset data into event queue when sync is configured

### ISSUE THREAD

**Issue by derek-pryor** [gigantum/hybrid-object-store#39]
When sync is configured with a dataset that already has data, the existing data needs to be loaded into the event queue that drives the sync service so it will populate the existing data.

**Tasks**
- [x] Update populated config to have a new channel field to send manually created bucket events
- [x] In API notification handler, on sync enable, create a new goroutine that takes the S3 client and channel and pushes on messages for all items in the bucket
- [x] In populated muxer, when creating core service configs, create a new channel
- [x] In demuxer startup, after notification queue goroutine startup, do a similar thing for the new channel. Push the messages from this channel onto the central notification channel for processing
